version: "3"
services:
  app:
    env_file: ./.env
    container_name: 'node19'
    image: node:19
    working_dir: /usr/src/app
    tty: true
    ports:
    - '3000:3000'
    volumes:
      - ./:/usr/src/app
    user: "1000:1000"
    command: >
      bash -c "yarn && yarn dev"